services:
  db:
    image: mysql:8.0.41  # Example to use MySQL 8.0 instead of latest
    environment:
      MYSQL_ROOT_PASSWORD: DT1APD!
    ports:
      - "3306:3306"
    volumes:
      - dobid_database:/var/lib/mysql
      - ./setup_mysql.sql:/docker-entrypoint-initdb.d/setup_mysql.sql
    networks:
      - lamp-docker

  createmore_admin:
    build: .
    depends_on:
      - db
    volumes:
      - /c/wamp64/www/createmore_admin:/var/www/html/createmore_admin
    ports:
      - "8181:80"
      - "443:443"
    networks:
      - lamp-docker
networks:
  lamp-docker:
    driver: bridge

volumes:
  dobid_database:
    driver: local
